# Generated by Django 5.1.4 on 2025-02-11 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='profile_pic',
            field=models.ImageField(default='', upload_to='contact_pic'),
        ),
    ]
